export const homeTown = [
  "Alone",
  "Student Accommodation",
  "With Roommates",
  "Traveling",
  "With Family",
  "Prefer Not To Say",
];

export const schoolDegree = [
  "High School",
  "Associates",
  "Bachelor's",
  "Graduate",
  "Masters",
  "Doctorate",
  "Prefer Not To Say",
];

export const haveChild = ["Yes", "No", "Prefer Not To Say"];

export const wantChild = ["Yes", "No", "Open", "Prefer Not To Say"];

export const height = [
  91.46, 94.488, 97.536, 99.568, 100.584, 103.632, 106.68, 109.728, 112.776,
  114.3, 115.824, 118.872, 121.92, 124.968, 127.0, 129.5, 132.1, 134.6, 137.2,
  139.7, 142.2, 145.0, 147.0, 150.0, 152.4, 155.0, 158.0, 160.0, 163.0, 165.0,
  168.0, 170.0, 173.0, 175.0, 178.0, 180.0, 183.0, 185.0, 188.0, 191.0, 193.0,
  195.0, 198.0, 201.0, 203.0,
];

export const bodyType = [
  "Average",
  "Athletic",
  "Muscular",
  "thin",
  "Curvy",
  "Big & Bold",
  "Prefer no to say",
];

export const diet = [
  "Everything",
  "Athletic",
  "Vegetarian",
  "Vegan",
  "Pascatarian",
  "Gluten free",
  "Lactose free",
  "Kosher",
  "Islamic",
  "Prefer not to say",
];

export const fitness = [
  "Never",
  "Once a week",
  "2-4 times a week",
  "5+ times a week",
  "Prefer not to say",
];

export const race = [
  "American Indian",
  "Black/ African",
  "Middle Eastern",
  "Hispanic/ Latin",
  "East Asian",
  "Pacific Islander",
  "South Asian",
  "White/ Caucasian",
  "Other",
  "Two or More Races",
  "Prefer not to say",
];

export const religion = [
  "Buddhist",
  "Catholic",
  "Christian",
  "Hindu",
  "Jewish",
  "Muslim",
  "Spiritual",
  "Agnostic",
  "Athiest",
  "Other",
  "Prefer Not To say",
];

export const politics = [
  "Liberal",
  "Conservative",
  "Moderate",
  "Other",
  "Prefer not to say",
];

export const gender = [
  "Male",
  "Female",
  "Agender",
  "Androgyne",
  "Androgynous",
  "Bigender",
  "Cis",
  "Cisgender",
  "Cis Female",
  "Cis Male",
  "Cis Man",
  "Cis Woman",
  "Cisgender Female",
  "Cisgender Male",
  "Cisgender Man",
  "Cisgender Woman",
  "Female to Male",
  "FTM",
  "Gender Fluid",
  "Gender Nonconforming",
  "Gender Questioning",
  "Gender Variant",
  "Genderqueer",
  "Intersex",
  "Male to Female",
  "MTF",
  "Neither",
  "Neutrois",
  "Non-binary",
  "Pangender",
  "Trans",
  "Trans*",
  "Trans Female",
  "Trans* Female",
  "Trans Male",
  "Trans* Male",
  "Trans Man",
  "Trans* Man",
  "Trans Person",
  "Trans* Person",
  "Trans Woman",
  "Trans* Woman",
  "Trans feminine",
  "Transgender",
  "Transgender Female",
  "Transgender Male",
  "Transgender Man",
  "Transgender Person",
  "Transgender Woman",
  "Trans masculine",
  "Transsexual",
  "Transsexual Female",
  "Transsexual Male",
  "Transsexual Man",
  "Transsexual Person",
  "Transsexual Woman",
  "Two-Spirit",
  "Other",
];

export const countryList = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "AmericanSamoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia, Plurinational State of",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, The Democratic Republic of the Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See (Vatican City State",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of Persian Gulf",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of Korea",
  "Korea, Republic of South Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",

  "Micronesia, Federated States of Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Reunion",
  "Saint Barthelemy",
  "Saint Helena, Ascension and Tristan Da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "South Georgia and the South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela, Bolivarian Republic of Venezuela",
  "Vietnam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const ethnicityList = [
  "American Indian",
  "Black/ African",
  "East Asian",
  "Hispanic/ Latin",
  "Middle Eastern",
  "Pacific Islander",
  "South Asian",
  "White/ Caucasian",
  "Other",
  "Prefer not to say",
];
